arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - waist
    - shoulder
    - elbow
    - forearm_roll
    - wrist_angle
    - wrist_rotate
  gains: # Required because we're controlling an effort interface
    waist: {p: 100.0,  d: 1.0, i: 5.0}
    shoulder: {p: 500.0,  d: 1.0, i: 10.0}
    elbow: {p: 300.0,  d: 1.0, i: 10.0}
    forearm_roll: {p: 5.0,  d: 0, i: 0}
    wrist_angle: {p: 100.0,  d: 1.0, i: 3.0}
    wrist_rotate: {p: 100.0,  d: 0.1, i: 1.0}
  
  constraints:
    goal_time: 0.4
    waist:
      goal: 0.4
      trajectory: 0.4
    shoulder:
      goal: 0.4
      trajectory: 0.4
    elbow:
      goal: 0.4
      trajectory: 0.4
    forearm_roll:
      goal: 0.4
      trajectory: 0.4
    wrist_angle:
      goal: 0.4
      trajectory: 0.4
    wrist_rotate:
      goal: 0.4
      trajectory: 0.4

  # constraints:
  #   goal_time: 0.2
  #   waist:
  #     goal: 0.2
  #     trajectory: 0.2
  #   shoulder:
  #     goal: 0.2
  #     trajectory: 0.2
  #   elbow:
  #     goal: 0.2
  #     trajectory: 0.2
  #   forearm_roll:
  #     goal: 0.2
  #     trajectory: 0.2
  #   wrist_angle:
  #     goal: 0.2
  #     trajectory: 0.2
  #   wrist_rotate:
  #     goal: 0.2
  #     trajectory: 0.2

  # constraints:
  #   goal_time: 0.2
  #   waist:
  #     goal: 0.1
  #     trajectory: 0.1
  #   shoulder:
  #     goal: 0.1
  #     trajectory: 0.1
  #   elbow:
  #     goal: 0.1
  #     trajectory: 0.1
  #   forearm_roll:
  #     goal: 0.1
  #     trajectory: 0.1
  #   wrist_angle:
  #     goal: 0.1
  #     trajectory: 0.1
  #   wrist_rotate:
  #     goal: 0.1
  #     trajectory: 0.1

gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_finger
    - right_finger
  gains:
    left_finger: {p: 100.0,  d: 1.0, i: 0.0}
    right_finger: {p: 100.0,  d: 1.0, i: 0.0}
  
  constraints:
    goal_time: 0.2
    left_finger:
      goal: 0.2
      trajectory: 0.2
    right_finger:
      goal: 0.2
      trajectory: 0.2

  initial:  # Define initial robot poses per group
  - group: interbotix_arm
    pose: Sleep
